export interface FormResult {
    firstName: string,
    lastName: string,
    studentID: string,
    school: string,
    major: string,
    categories: Array<String>,
    leadershipCategory: Array<Object>,
    clubCategory: Array<Object>,
    devCategory: Array<Object>,
    wellnessCategory: Array<Object>,
    campusCategory: Array<Object>,
    communityCategory: Array<Object>,
    globalCategory: Array<Object>,
    academicCategory: Array<Object>,
    officialCategory: Array<Object>,
    peerCategory: Array<Object>,
    athleticsCategory: Array<Object>,
    creativeCategory: Array<Object>,
    awardCategory: Array<Object>,
    otherCategory: Array<Object>,
    date: string
}
